### ISSUE TITLE
 path to the checkpoint

### ISSUE THREAD

**Issue by msandroid** [kingzcheung/ComfyUI_kkTranslator_nodes#2]
Question 1-Which checkpoint path is referenced by loadmarianmtcheckpointnode?

https://huggingface.co/Helsinki-NLP/opus-mt-ja-en
I want to use this 👆.

**Comment by kingzcheung** [comment]
![image](https://github.com/kingzcheung/ComfyUI_kkTranslator_nodes/assets/12839855/273c3970-b485-4fb4-821a-a11eccc0f04e)
